<?php

namespace Walva\SimpleCmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbstractContentDelivererRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractContentDelivererRepository extends EntityRepository
{
}
